apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . | trunc 20}}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-reader
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}
