# This rule is not used by the project k8sgpt-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.k8sgpt.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sgpt-operator
    app.kubernetes.io/managed-by: kustomize
  name: mutation-viewer-role
rules:
- apiGroups:
  - core.k8sgpt.ai
  resources:
  - mutations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.k8sgpt.ai
  resources:
  - mutations/status
  verbs:
  - get
