# permissions for end users to edit results.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sgpt-operator
    app.kubernetes.io/managed-by: kustomize
  name: result-editor-role
rules:
- apiGroups:
  - core.k8sgpt.ai
  resources:
  - results
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.k8sgpt.ai
  resources:
  - results/status
  verbs:
  - get
