---
customMetrics:
  - metric: k8sgpt_reconcile_error_count
    type: counter
    unit: cpm
  - metric: k8sgpt_number_of_results
    type: gauge
  - metric: k8sgpt_number_of_results_by_type
    type: gauge
#  - metric: # Raw custom metric (required)
#    type:   # Metric type: counter/gauge/histogram (required)
#    expr:   # Prom_ql for the metric (optional)
#    unit:   # Unit of measurement, examples: s,none,bytes,percent,etc. (optional)
#
#
# Example:
# ---
# customMetrics:
#   - metric: foo_bar
#     unit: none
#     type: histogram
#   	expr: histogram_quantile(0.90, sum by(instance, le) (rate(foo_bar{job=\"$job\", namespace=\"$namespace\"}[5m])))
