apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-auto-remediation-sample
spec:
  ai:
    autoRemediation:
      enabled: true
      similarityRequirement: "90"
      resources:
        - Pod
        - Service
        - Deployment
    enabled: true
    model: gpt-4o-mini
    backend: openai
    secret:
      name: k8sgpt-sample-secret
      key: openai-api-key
  remoteCache:
    interplex:
      endpoint: release-interplex-service.k8sgpt-operator-system.svc.cluster.local:8084
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.1
